/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cantina.vista;
import java.awt.Component;

/**
 *
 * @author danie
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        logicon = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        contUser = new javax.swing.JPanel();
        userLogin = new javax.swing.JTextField();
        usrSeparator = new javax.swing.JSeparator();
        contPass = new javax.swing.JPanel();
        passLogin = new javax.swing.JPasswordField();
        passSeparator = new javax.swing.JSeparator();
        contenedorBtnLogin = new javax.swing.JPanel();
        relleno1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        relleno2 = new javax.swing.JPanel();
        btnForgotPass = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setBackground(new java.awt.Color(153, 153, 255));
        contenedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        contenedor.setAlignmentX(0.0F);
        contenedor.setAlignmentY(0.0F);
        contenedor.setPreferredSize(new java.awt.Dimension(700, 500));
        contenedor.setLayout(new java.awt.GridLayout(6, 1));

        logicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_user_locked_50px.png"))); // NOI18N
        logicon.setAlignmentX(2.0F);
        contenedor.add(logicon);
        logicon.setAlignmentX(Component.CENTER_ALIGNMENT);

        labelLogin.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogin.setText("INICIAR SESIÓN");
        labelLogin.setAlignmentX(2.0F);
        contenedor.add(labelLogin);
        //labelLogin.setAlignmentX(javax.awt.Component.CENTER_ALIGNMENT);

        contUser.setBackground(new java.awt.Color(153, 153, 255));
        contUser.setLayout(new java.awt.BorderLayout());

        userLogin.setBackground(new java.awt.Color(153, 153, 255));
        userLogin.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        userLogin.setForeground(new java.awt.Color(102, 102, 102));
        userLogin.setText("usuario");
        userLogin.setBorder(null);
        userLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userLogin.setMargin(new java.awt.Insets(2, 50, 2, 2));
        userLogin.setPreferredSize(new java.awt.Dimension(90, 10));
        contUser.add(userLogin, java.awt.BorderLayout.CENTER);

        usrSeparator.setBackground(new java.awt.Color(0, 0, 0));
        usrSeparator.setForeground(new java.awt.Color(0, 0, 0));
        usrSeparator.setRequestFocusEnabled(false);
        usrSeparator.setVerifyInputWhenFocusTarget(false);
        contUser.add(usrSeparator, java.awt.BorderLayout.PAGE_END);

        contenedor.add(contUser);

        contPass.setBackground(new java.awt.Color(153, 153, 255));
        contPass.setLayout(new java.awt.BorderLayout());

        passLogin.setBackground(new java.awt.Color(153, 153, 255));
        passLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passLogin.setForeground(new java.awt.Color(102, 102, 102));
        passLogin.setText("jPasswordField1");
        passLogin.setBorder(null);
        passLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passLogin.setMargin(new java.awt.Insets(2, 20, 2, 2));
        passLogin.setPreferredSize(new java.awt.Dimension(90, 10));
        contPass.add(passLogin, java.awt.BorderLayout.CENTER);
        contPass.add(passSeparator, java.awt.BorderLayout.PAGE_END);

        contenedor.add(contPass);

        contenedorBtnLogin.setBackground(new java.awt.Color(153, 153, 255));
        contenedorBtnLogin.setLayout(new java.awt.GridLayout(1, 0));

        relleno1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout relleno1Layout = new javax.swing.GroupLayout(relleno1);
        relleno1.setLayout(relleno1Layout);
        relleno1Layout.setHorizontalGroup(
            relleno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        relleno1Layout.setVerticalGroup(
            relleno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        contenedorBtnLogin.add(relleno1);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        btnLogin.setText("ENTRAR");
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setName(""); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        contenedorBtnLogin.add(jPanel1);

        relleno2.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout relleno2Layout = new javax.swing.GroupLayout(relleno2);
        relleno2.setLayout(relleno2Layout);
        relleno2Layout.setHorizontalGroup(
            relleno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        relleno2Layout.setVerticalGroup(
            relleno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        contenedorBtnLogin.add(relleno2);

        contenedor.add(contenedorBtnLogin);

        btnForgotPass.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnForgotPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnForgotPass.setText("Olvidé mi contraseña");
        btnForgotPass.setAlignmentX(1.0F);
        contenedor.add(btnForgotPass);

        getContentPane().add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 560, 360));
        //contenedor.setLayout(new BoxLayout(outputPanel, BoxLayout.Y_AXIS));

        bg.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        setBounds(0, 0, 716, 539);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnForgotPass;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel contPass;
    private javax.swing.JPanel contUser;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel contenedorBtnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel logicon;
    private javax.swing.JPasswordField passLogin;
    private javax.swing.JSeparator passSeparator;
    private javax.swing.JPanel relleno1;
    private javax.swing.JPanel relleno2;
    private javax.swing.JTextField userLogin;
    private javax.swing.JSeparator usrSeparator;
    // End of variables declaration//GEN-END:variables
}
