/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cantina.vista;

import cantina.controlador.ArticulosControl;
import cantina.controlador.CategoriasControlador;
import cantina.modelo.Articulos;
import cantina.modelo.Categorias;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeListener;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ToolTipManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class MainPage extends javax.swing.JFrame {
    CategoriasControlador cc = new CategoriasControlador();
    ArticulosControl ac = new ArticulosControl();
    DefaultTableModel modelo;
    int item;
    int totalPagar=0;
     private int rolActual = 45;

    public int getRolActual() {
        return rolActual;
    }

    public void setRolActual(int rolActual) {
        this.rolActual = rolActual;
    }
    /**
     * Creates new form MainPage
     */
    public MainPage(int rolLogin) {

        initComponents();
        
        //System.out.println("Rol en mainpage: "+ rolLogin);
       
        setLocationRelativeTo(null);
         if(rolLogin == 1){
             //SI ES ADMINISTRADOR SE LE PREGUNTA SI QUIERE INGRESAR COMO VENDEDOR, PARA EVITAR MOSTRAR DEMASIADAS OPCIONES
             String[] options = new String[] {"Como Administrador", "Como Vendedor"};
             int respuesta = JOptionPane.showOptionDialog(null, "Con qué privilegios desea acceder?", "Elegir modo de priviegio",
                JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, options, options[0]);
             if(respuesta == 1){
                 modoVendedor();
             }
         }
         if(rolLogin == 2){
            modoVendedor();
        }
        MostrarComboCat();
        MostrarTabArti();
        fieldCod.requestFocus();
        ToolTipManager.sharedInstance().setInitialDelay(300);
         
         
    }
    
    public void modoVendedor(){
        tabsPanel.removeTabAt(4);
        tabsPanel.removeTabAt(3);
        btnConfig.setVisible(false);
        btnInformes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked"})
    private void MostrarComboCat(){
        this.jComboBox2Categorias.setModel(cc.Obt_Cat());
    }
   private void MostrarTabArti(){
       ac.cargar_tabla_arti(jTableArticulos);
       modelo = (DefaultTableModel) jTableArticulos.getModel();
   }
   private void LimpiarTable(){
       for (int i = 0; i < modelo.getRowCount() ; i++) {
           modelo.removeRow(i);
           i=i-1;
       }
   }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        sidebarMain = new javax.swing.JPanel();
        logoCont = new javax.swing.JPanel();
        mainLogo = new javax.swing.JLabel();
        contSidebarButtons = new javax.swing.JPanel();
        btnNewVenta = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnInformes = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        mainTitle = new javax.swing.JLabel();
        tabsPanel = new javax.swing.JTabbedPane();
        panelNuevaVenta = new javax.swing.JPanel();
        contMainVenta = new javax.swing.JPanel();
        contPanelEntrada = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        fieldCod = new javax.swing.JTextField();
        labCod = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fieldId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fieldDesc = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fieldCant = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        fieldPrecUnit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fieldPrecTotal = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        fieldStock = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVentaItems = new javax.swing.JTable();
        contCierreVenta = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldTotalPagar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        panelProductos = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        panelContEntradaProductos = new javax.swing.JPanel();
        contSidebarT2 = new javax.swing.JPanel();
        contBtnProductos = new javax.swing.JPanel();
        btnActualizarProductos = new javax.swing.JButton();
        btnBorrarProducto = new javax.swing.JButton();
        btnGuardarProducto = new javax.swing.JButton();
        btnExportProduc = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        contInsertProd = new javax.swing.JPanel();
        labT2Cod = new javax.swing.JLabel();
        labT2Desc = new javax.swing.JLabel();
        labT2StockDisp = new javax.swing.JLabel();
        labT2PrecioCosto = new javax.swing.JLabel();
        fieldT2Cod = new javax.swing.JTextField();
        fieldT2Desc = new javax.swing.JTextField();
        fieldT2Cant = new javax.swing.JTextField();
        fieldT2PrecioCosto = new javax.swing.JTextField();
        labT2PrecioVenta = new javax.swing.JLabel();
        fieldT2PrecioVenta = new javax.swing.JTextField();
        labT2Categorias = new javax.swing.JLabel();
        jComboBox2Categorias = new javax.swing.JComboBox<>();
        fieldT2Id = new javax.swing.JTextField();
        labT2Cod1 = new javax.swing.JLabel();
        btnLimpiarProd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        contenedorTablat2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableArticulos = new javax.swing.JTable();
        panelVentas = new javax.swing.JPanel();
        contBotonesVentas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnResumenVentasDiario = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableVentas = new javax.swing.JTable();
        panelConfig = new javax.swing.JPanel();
        panelInformes = new javax.swing.JPanel();
        panelCajero = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1110, 580));
        setPreferredSize(new java.awt.Dimension(1110, 580));

        sidebarMain.setBackground(new java.awt.Color(103, 226, 109));
        sidebarMain.setPreferredSize(new java.awt.Dimension(135, 600));

        logoCont.setBackground(new java.awt.Color(103, 226, 109));
        logoCont.setPreferredSize(new java.awt.Dimension(120, 120));
        logoCont.setLayout(new java.awt.GridLayout(1, 0));

        mainLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_online_shopping_100px_1.png"))); // NOI18N
        logoCont.add(mainLogo);

        contSidebarButtons.setBackground(new java.awt.Color(103, 226, 109));
        contSidebarButtons.setLayout(new java.awt.GridBagLayout());

        btnNewVenta.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnNewVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_receive_cash_30px.png"))); // NOI18N
        btnNewVenta.setText("Nueva Venta");
        btnNewVenta.setToolTipText("Ir a la pestaña Nueva Venta");
        btnNewVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewVentaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNewVentaMouseReleased(evt);
            }
        });
        btnNewVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewVentaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 10);
        contSidebarButtons.add(btnNewVenta, gridBagConstraints);

        btnProductos.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_empty_box_30px.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setToolTipText("Ir a la pestaña Productos");
        btnProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnProductosMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 10);
        contSidebarButtons.add(btnProductos, gridBagConstraints);

        btnConfig.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_settings_30px.png"))); // NOI18N
        btnConfig.setText("Configuración");
        btnConfig.setToolTipText("Ir a la pestaña Configuración");
        btnConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfigMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnConfigMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 10);
        contSidebarButtons.add(btnConfig, gridBagConstraints);

        btnVentas.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_list_30px.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setToolTipText("Ir a la pestaña Ventas");
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentasMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVentasMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 10);
        contSidebarButtons.add(btnVentas, gridBagConstraints);

        btnInformes.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_upload_link_document_30px.png"))); // NOI18N
        btnInformes.setText("Informes");
        btnInformes.setToolTipText("Ir a la pestaña Informes");
        btnInformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInformesMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnInformesMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 10);
        contSidebarButtons.add(btnInformes, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(103, 226, 109));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weighty = 0.25;
        contSidebarButtons.add(jPanel4, gridBagConstraints);

        jPanel13.setBackground(new java.awt.Color(103, 226, 109));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.25;
        contSidebarButtons.add(jPanel13, gridBagConstraints);

        javax.swing.GroupLayout sidebarMainLayout = new javax.swing.GroupLayout(sidebarMain);
        sidebarMain.setLayout(sidebarMainLayout);
        sidebarMainLayout.setHorizontalGroup(
            sidebarMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contSidebarButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(logoCont, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        sidebarMainLayout.setVerticalGroup(
            sidebarMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarMainLayout.createSequentialGroup()
                .addComponent(logoCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contSidebarButtons, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
        );

        getContentPane().add(sidebarMain, java.awt.BorderLayout.WEST);

        header.setBackground(new java.awt.Color(103, 226, 109));

        mainTitle.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(255, 255, 255));
        mainTitle.setText("CANTINA ANGLO");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(mainTitle)
                .addContainerGap(874, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainTitle)
                .addGap(20, 20, 20))
        );

        getContentPane().add(header, java.awt.BorderLayout.NORTH);

        panelNuevaVenta.setBackground(new java.awt.Color(103, 226, 109));
        panelNuevaVenta.setLayout(new java.awt.BorderLayout());

        contMainVenta.setLayout(new java.awt.BorderLayout());

        contPanelEntrada.setLayout(new java.awt.GridBagLayout());

        fieldCod.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fieldCod.setToolTipText("Escanea el producto con tu lector");

        labCod.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labCod.setText("Cód. de Barras");
        labCod.setToolTipText("Escanea el producto con tu lector");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldCod)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labCod, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labCod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 7);
        contPanelEntrada.add(jPanel1, gridBagConstraints);

        fieldId.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fieldId.setToolTipText("Código único de producto en el inventario");

        jLabel12.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel12.setText("Id Producto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fieldId)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 7);
        contPanelEntrada.add(jPanel2, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel2.setText("Descripción");

        fieldDesc.setEditable(false);
        fieldDesc.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fieldDesc.setToolTipText("Descripción del producto");
        fieldDesc.setFocusable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 7);
        contPanelEntrada.add(jPanel3, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel3.setText("Cantidad");

        fieldCant.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fieldCant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldCantFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldCant, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 7);
        contPanelEntrada.add(jPanel6, gridBagConstraints);

        fieldPrecUnit.setEditable(false);
        fieldPrecUnit.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel4.setText("Precio Unitario");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldPrecUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldPrecUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 7);
        contPanelEntrada.add(jPanel7, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel6.setText("Prec. Total");

        fieldPrecTotal.setEditable(false);
        fieldPrecTotal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fieldPrecTotal.setToolTipText("Precio Unitario x Cantidad");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldPrecTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldPrecTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 7);
        contPanelEntrada.add(jPanel8, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel5.setText("Stock Disponible");

        fieldStock.setEditable(false);
        fieldStock.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fieldStock.setToolTipText("Cantidad restante de este producto en inventario");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldStock))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 7);
        contPanelEntrada.add(jPanel9, gridBagConstraints);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_clear_symbol_30px.png"))); // NOI18N
        jButton1.setToolTipText("Limpiar los campos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 7);
        contPanelEntrada.add(jPanel10, gridBagConstraints);

        contMainVenta.add(contPanelEntrada, java.awt.BorderLayout.NORTH);

        jTableVentaItems.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTableVentaItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Nº", "ID", "CODIGO", "DESCRIPCION", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableVentaItems);
        if (jTableVentaItems.getColumnModel().getColumnCount() > 0) {
            jTableVentaItems.getColumnModel().getColumn(6).setPreferredWidth(40);
        }

        contMainVenta.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        contCierreVenta.setPreferredSize(new java.awt.Dimension(468, 80));

        jButton2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_request_money_30px.png"))); // NOI18N
        jButton2.setText("Cerrar Venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel1.setText("Total a Cobrar:");

        fieldTotalPagar.setEditable(false);
        fieldTotalPagar.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        fieldTotalPagar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldTotalPagar.setText("21.500");
        fieldTotalPagar.setPreferredSize(new java.awt.Dimension(50, 21));

        jLabel13.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel13.setText("Gs.");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(fieldTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel13))
        );

        javax.swing.GroupLayout contCierreVentaLayout = new javax.swing.GroupLayout(contCierreVenta);
        contCierreVenta.setLayout(contCierreVentaLayout);
        contCierreVentaLayout.setHorizontalGroup(
            contCierreVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contCierreVentaLayout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        contCierreVentaLayout.setVerticalGroup(
            contCierreVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        contMainVenta.add(contCierreVenta, java.awt.BorderLayout.SOUTH);

        panelNuevaVenta.add(contMainVenta, java.awt.BorderLayout.CENTER);

        tabsPanel.addTab("", new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_receive_cash_30px.png")), panelNuevaVenta, ""); // NOI18N

        panelProductos.setLayout(new javax.swing.BoxLayout(panelProductos, javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setDividerSize(0);

        contSidebarT2.setMinimumSize(new java.awt.Dimension(332, 200));
        contSidebarT2.setPreferredSize(new java.awt.Dimension(332, 580));
        contSidebarT2.setLayout(new java.awt.GridBagLayout());

        contBtnProductos.setMaximumSize(new java.awt.Dimension(330, 175));
        contBtnProductos.setMinimumSize(new java.awt.Dimension(330, 175));
        contBtnProductos.setPreferredSize(new java.awt.Dimension(330, 175));

        btnActualizarProductos.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        btnActualizarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_edit_property_30px.png"))); // NOI18N
        btnActualizarProductos.setText("MODIFICAR");
        btnActualizarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProductosActionPerformed(evt);
            }
        });

        btnBorrarProducto.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        btnBorrarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_eraser_30px.png"))); // NOI18N
        btnBorrarProducto.setText("BORRAR");
        btnBorrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarProductoActionPerformed(evt);
            }
        });

        btnGuardarProducto.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        btnGuardarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_add_30px.png"))); // NOI18N
        btnGuardarProducto.setText("AGREGAR");
        btnGuardarProducto.setToolTipText("Guarda los datos en un nuevo registro");
        btnGuardarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProductoActionPerformed(evt);
            }
        });

        btnExportProduc.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        btnExportProduc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_spreadsheet_file_30px.png"))); // NOI18N
        btnExportProduc.setText("EXPORTAR");

        javax.swing.GroupLayout contBtnProductosLayout = new javax.swing.GroupLayout(contBtnProductos);
        contBtnProductos.setLayout(contBtnProductosLayout);
        contBtnProductosLayout.setHorizontalGroup(
            contBtnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contBtnProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contBtnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(btnBorrarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(contBtnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contBtnProductosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnActualizarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contBtnProductosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExportProduc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        contBtnProductosLayout.setVerticalGroup(
            contBtnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contBtnProductosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(contBtnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarProducto)
                    .addComponent(btnActualizarProductos))
                .addGap(18, 18, 18)
                .addGroup(contBtnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarProducto)
                    .addComponent(btnExportProduc))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 0.15;
        gridBagConstraints.weighty = 0.15;
        contSidebarT2.add(contBtnProductos, gridBagConstraints);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setMinimumSize(new java.awt.Dimension(264, 250));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(264, 250));
        jScrollPane4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jScrollPane4ComponentResized(evt);
            }
        });

        labT2Cod.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        labT2Cod.setText("ID Producto:");

        labT2Desc.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        labT2Desc.setText("Descripción:");

        labT2StockDisp.setFont(new java.awt.Font("Roboto Black", 0, 13)); // NOI18N
        labT2StockDisp.setText("Stock disponible:");

        labT2PrecioCosto.setFont(new java.awt.Font("Roboto Black", 0, 13)); // NOI18N
        labT2PrecioCosto.setText("Precio de Costo:");

        fieldT2Cod.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N

        fieldT2Desc.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N

        fieldT2Cant.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N

        fieldT2PrecioCosto.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N

        labT2PrecioVenta.setFont(new java.awt.Font("Roboto Black", 0, 13)); // NOI18N
        labT2PrecioVenta.setText("Precio de Venta:");

        fieldT2PrecioVenta.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        fieldT2PrecioVenta.setToolTipText("Recuerda usar valores redondeados para optimizar cobro.");

        labT2Categorias.setFont(new java.awt.Font("Roboto Black", 0, 13)); // NOI18N
        labT2Categorias.setText("Categorias:");

        jComboBox2Categorias.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jComboBox2Categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        fieldT2Id.setEditable(false);
        fieldT2Id.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        fieldT2Id.setToolTipText("No te preocupes por este campo, se rellenará automáticamente.");
        fieldT2Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldT2IdActionPerformed(evt);
            }
        });

        labT2Cod1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        labT2Cod1.setText("Código:");

        btnLimpiarProd.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnLimpiarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_eraser_tool_20px.png"))); // NOI18N
        btnLimpiarProd.setText("Limpiar Campos");
        btnLimpiarProd.setToolTipText("");
        btnLimpiarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarProdActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_add_20px_1.png"))); // NOI18N
        jLabel8.setToolTipText("Agregar nueva categoría");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout contInsertProdLayout = new javax.swing.GroupLayout(contInsertProd);
        contInsertProd.setLayout(contInsertProdLayout);
        contInsertProdLayout.setHorizontalGroup(
            contInsertProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contInsertProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contInsertProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(contInsertProdLayout.createSequentialGroup()
                        .addGroup(contInsertProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labT2Desc)
                            .addComponent(labT2StockDisp)
                            .addComponent(labT2PrecioCosto)
                            .addComponent(labT2PrecioVenta)
                            .addComponent(labT2Cod1)
                            .addComponent(labT2Cod))
                        .addGap(26, 26, 26))
                    .addGroup(contInsertProdLayout.createSequentialGroup()
                        .addComponent(labT2Categorias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(contInsertProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiarProd)
                    .addComponent(fieldT2Id, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contInsertProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fieldT2PrecioVenta, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fieldT2PrecioCosto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fieldT2Cant, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fieldT2Desc, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox2Categorias, 0, 165, Short.MAX_VALUE))
                    .addComponent(fieldT2Cod, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        contInsertProdLayout.setVerticalGroup(
            contInsertProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contInsertProdLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnLimpiarProd)
                .addGap(20, 20, 20)
                .addGroup(contInsertProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labT2Cod)
                    .addComponent(fieldT2Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(contInsertProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labT2Cod1)
                    .addComponent(fieldT2Cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(contInsertProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labT2Desc)
                    .addComponent(fieldT2Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(contInsertProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labT2StockDisp)
                    .addComponent(fieldT2Cant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(contInsertProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labT2PrecioCosto)
                    .addComponent(fieldT2PrecioCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(contInsertProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labT2PrecioVenta)
                    .addComponent(fieldT2PrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(contInsertProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labT2Categorias)
                    .addComponent(jComboBox2Categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(contInsertProd);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.85;
        gridBagConstraints.weighty = 0.85;
        contSidebarT2.add(jScrollPane4, gridBagConstraints);

        javax.swing.GroupLayout panelContEntradaProductosLayout = new javax.swing.GroupLayout(panelContEntradaProductos);
        panelContEntradaProductos.setLayout(panelContEntradaProductosLayout);
        panelContEntradaProductosLayout.setHorizontalGroup(
            panelContEntradaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contSidebarT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelContEntradaProductosLayout.setVerticalGroup(
            panelContEntradaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContEntradaProductosLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(contSidebarT2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(panelContEntradaProductos);

        jTableArticulos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTableArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableArticulosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableArticulos);

        javax.swing.GroupLayout contenedorTablat2Layout = new javax.swing.GroupLayout(contenedorTablat2);
        contenedorTablat2.setLayout(contenedorTablat2Layout);
        contenedorTablat2Layout.setHorizontalGroup(
            contenedorTablat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );
        contenedorTablat2Layout.setVerticalGroup(
            contenedorTablat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorTablat2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(contenedorTablat2);

        panelProductos.add(jSplitPane1);

        tabsPanel.addTab("", new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_empty_box_30px.png")), panelProductos); // NOI18N

        panelVentas.setLayout(new javax.swing.BoxLayout(panelVentas, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("Genera tus resúmenes");

        btnResumenVentasDiario.setFont(new java.awt.Font("Roboto Light", 1, 15)); // NOI18N
        btnResumenVentasDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_pdf_30px.png"))); // NOI18N
        btnResumenVentasDiario.setText("Hoy");

        jButton3.setFont(new java.awt.Font("Roboto Light", 1, 15)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_pdf_30px.png"))); // NOI18N
        jButton3.setText("Últimos 7 días");

        jButton4.setFont(new java.awt.Font("Roboto Light", 1, 15)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_pdf_30px.png"))); // NOI18N
        jButton4.setText("Mes Actual");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Roboto Light", 1, 15)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_pdf_30px.png"))); // NOI18N
        jButton5.setText("Año Actual");

        jTableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "VENDEDOR", "TOTAL"
            }
        ));
        jScrollPane3.setViewportView(jTableVentas);
        if (jTableVentas.getColumnModel().getColumnCount() > 0) {
            jTableVentas.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableVentas.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTableVentas.getColumnModel().getColumn(2).setPreferredWidth(60);
        }

        javax.swing.GroupLayout contBotonesVentasLayout = new javax.swing.GroupLayout(contBotonesVentas);
        contBotonesVentas.setLayout(contBotonesVentasLayout);
        contBotonesVentasLayout.setHorizontalGroup(
            contBotonesVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contBotonesVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contBotonesVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contBotonesVentasLayout.createSequentialGroup()
                        .addGroup(contBotonesVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(contBotonesVentasLayout.createSequentialGroup()
                                .addComponent(btnResumenVentasDiario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addGap(10, 10, 10)
                                .addComponent(jButton4)
                                .addGap(10, 10, 10)
                                .addComponent(jButton5)))
                        .addContainerGap(465, Short.MAX_VALUE))
                    .addGroup(contBotonesVentasLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE)
                        .addGap(19, 19, 19))))
        );
        contBotonesVentasLayout.setVerticalGroup(
            contBotonesVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contBotonesVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jLabel7)
                .addGap(16, 16, 16)
                .addGroup(contBotonesVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnResumenVentasDiario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        panelVentas.add(contBotonesVentas);

        tabsPanel.addTab("", new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_list_30px.png")), panelVentas); // NOI18N

        javax.swing.GroupLayout panelConfigLayout = new javax.swing.GroupLayout(panelConfig);
        panelConfig.setLayout(panelConfigLayout);
        panelConfigLayout.setHorizontalGroup(
            panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1071, Short.MAX_VALUE)
        );
        panelConfigLayout.setVerticalGroup(
            panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        tabsPanel.addTab("", new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_settings_30px.png")), panelConfig); // NOI18N

        javax.swing.GroupLayout panelInformesLayout = new javax.swing.GroupLayout(panelInformes);
        panelInformes.setLayout(panelInformesLayout);
        panelInformesLayout.setHorizontalGroup(
            panelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1071, Short.MAX_VALUE)
        );
        panelInformesLayout.setVerticalGroup(
            panelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        tabsPanel.addTab("", new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_upload_link_document_30px.png")), panelInformes); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1051, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelCajeroLayout = new javax.swing.GroupLayout(panelCajero);
        panelCajero.setLayout(panelCajeroLayout);
        panelCajeroLayout.setHorizontalGroup(
            panelCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCajeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCajeroLayout.setVerticalGroup(
            panelCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCajeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsPanel.addTab("Cajero", panelCajero);

        getContentPane().add(tabsPanel, java.awt.BorderLayout.CENTER);
        tabsPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewVentaActionPerformed

    private void btnProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnProductosMouseClicked

    private void btnNewVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewVentaMouseClicked
//        tabsPanel.setSelectedIndex(0);         

    }//GEN-LAST:event_btnNewVentaMouseClicked

    private void btnVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnVentasMouseClicked

    private void btnConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnConfigMouseClicked

    private void btnInformesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInformesMouseClicked

    private void btnNewVentaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewVentaMouseReleased
        // TODO add your handling code here:
         tabsPanel.setSelectedIndex(0);   
         fieldCod.requestFocus();
    }//GEN-LAST:event_btnNewVentaMouseReleased

    private void btnProductosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseReleased
        // TODO add your handling code here:
        tabsPanel.setSelectedIndex(1); 
    }//GEN-LAST:event_btnProductosMouseReleased

    private void btnVentasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseReleased
        // TODO add your handling code here:
         tabsPanel.setSelectedIndex(2); 
    }//GEN-LAST:event_btnVentasMouseReleased

    private void btnConfigMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseReleased
        // TODO add your handling code here:
         tabsPanel.setSelectedIndex(3); 
    }//GEN-LAST:event_btnConfigMouseReleased

    private void btnInformesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformesMouseReleased
        // TODO add your handling code here:
         tabsPanel.setSelectedIndex(4); 
    }//GEN-LAST:event_btnInformesMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jScrollPane4ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jScrollPane4ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane4ComponentResized

    private void btnGuardarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProductoActionPerformed
        // TODO add your handling code here:
        int flag = 0;
        try{
            Integer idarticulo = null;
            ArticulosControl ac = new ArticulosControl();
            Integer precioVenta = null;
            Integer precioCosto = null;
            Integer stock = null;
            String Codigo = fieldT2Cod.getText();
            String descripcion = fieldT2Desc.getText();
            String stockStr = fieldT2Cant.getText();
            String precioCStr = fieldT2PrecioCosto.getText();
            String precioVStr = fieldT2PrecioVenta.getText();
            Integer categoria= null;
            Categorias cat=null;
            Boolean estado = true;
                    
            if (jComboBox2Categorias.getSelectedIndex() != 0){
                categoria = jComboBox2Categorias.getSelectedIndex();
                cat = new CategoriasControlador().buscarId(categoria);
            }
                        
            if (stockStr != null) {
                stock = Integer.parseInt(stockStr);
            }
            if (precioCStr != null) {
                precioCosto = Integer.parseInt(precioCStr);
            }
            if (precioVStr !=null){
                precioVenta = Integer.parseInt(precioVStr);
            }
            
            Articulos a = null; 
            a = new Articulos(idarticulo, Codigo, precioCosto, descripcion, 
                    estado, precioVenta, stock, cat);
            ac.insertar(a);
            LimpiarProd();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Hubo un error en la carga del articulo, por favor intente de nuevo\n"+e,
                    "Error en la carga",2);
            flag =1;
        }
        if (flag == 0){
            JOptionPane.showMessageDialog(null, "Articulo guardado");
        }
        MostrarTabArti();
    }//GEN-LAST:event_btnGuardarProductoActionPerformed

    private void btnBorrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarProductoActionPerformed
        // TODO add your handling code here:
        try{
            if (!"".equals(fieldT2Id.getText())){
                int pregunta = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar este producto?");
                if (pregunta==0){
                    int id = Integer.parseInt(fieldT2Id.getText());
                    ac.eliminarIdLogico(id);
                    LimpiarTable();
                    LimpiarProd();
                    MostrarTabArti();
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btnBorrarProductoActionPerformed

    private void jTableArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableArticulosMouseClicked
        // TODO add your handling code here:
        int fila = jTableArticulos.rowAtPoint(evt.getPoint());
        fieldT2Id.setText(jTableArticulos.getValueAt(fila, 0).toString());
        fieldT2Cod.setText(jTableArticulos.getValueAt(fila, 1).toString());
        fieldT2Desc.setText(jTableArticulos.getValueAt(fila, 2).toString());
        fieldT2Cant.setText(jTableArticulos.getValueAt(fila, 3).toString());
        fieldT2PrecioCosto.setText(jTableArticulos.getValueAt(fila, 4).toString());
        fieldT2PrecioVenta.setText(jTableArticulos.getValueAt(fila, 5).toString());
        jComboBox2Categorias.setSelectedItem(jTableArticulos.getValueAt(fila, 6).toString());
    }//GEN-LAST:event_jTableArticulosMouseClicked

    private void btnActualizarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProductosActionPerformed
        // TODO add your handling code here:
        if (!"".equals(fieldT2Cod.getText())){
            
            String[] options = new String[2];
            options[0] = "SÍ";
            options[1] = "NO";
            int pregunta = JOptionPane.showOptionDialog(getContentPane(), "¿Esta seguro de que quiere MODIFICAR este producto?", "Confirmar Modificación", 0, JOptionPane.INFORMATION_MESSAGE, null, options, null);

            //int pregunta = JOptionPane.showConfirmDialog(null, "¿Esta seguro de Modificar este producto?");
            if (pregunta==0){
                
                try{
                    Integer idarticulo = Integer.parseInt(fieldT2Id.getText());
                    ArticulosControl ac = new ArticulosControl();
                    Integer precioVenta = Integer.parseInt(fieldT2PrecioVenta.getText());;
                    Integer precioCosto = Integer.parseInt(fieldT2PrecioCosto.getText());
                    Integer stock = Integer.parseInt(fieldT2Cant.getText());
                    String Codigo = fieldT2Cod.getText();
                    String descripcion = fieldT2Desc.getText();
                    Integer categoria= jComboBox2Categorias.getSelectedIndex();;
                    Categorias cat = new CategoriasControlador().buscarId(categoria);;
                    Boolean estado = true; 
                    if (!"".equals(fieldT2PrecioVenta.getText()) && !"".equals(fieldT2Cod.getText()) && !"".equals(fieldT2Cant.getText())
                            && !"".equals(fieldT2Desc.getText()) && null!=cat){
                        Articulos a = new Articulos(idarticulo, Codigo, precioCosto, descripcion, 
                                estado, precioVenta, stock, cat);
                        ac.modificar(a);
                        LimpiarProd();
                        MostrarTabArti();
                    }else{
                        JOptionPane.showMessageDialog(null, "Algunos de los campos obligatorios estan vacios",
                                "Error en la Actualizacion", 1);
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Hubo un error en la Modificacion del articulo, "
                            + "por favor intente de nuevo\n"+e.getMessage(), "Error en la Modificacion",2);
                }
            }
        }
    }//GEN-LAST:event_btnActualizarProductosActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void fieldCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCodKeyPressed
        // TODO add your handling code here:
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                if(!"".equals(fieldCod.getText())){
                    String cod = fieldCod.getText();
                    Articulos a = ac.buscarCod(cod);
                    if(a.getDescripcion() != null){
                        fieldId.setText(a.getIdarticulo()+"");
                        fieldDesc.setText(a.getDescripcion());
                        fieldPrecUnit.setText(a.getPrecioVenta()+"");
                        fieldStock.setText(a.getStock().toString());
                        fieldCant.requestFocus();
                        
                        
                    }else{
                        limpiarVenta();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Escanee el codigo con el lector de codigo de barras o bien ingrese el id");
                    fieldCod.requestFocus();
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_fieldCodKeyPressed

    private void limpiarVenta(){
        fieldCod.setText("");
        fieldId.setText("");
        fieldDesc.setText("");
        fieldCant.setText("");
        fieldPrecUnit.setText("");
        fieldPrecTotal.setText("");
        fieldStock.setText("");
        fieldCod.requestFocus();
    }
    
    private void fieldCantFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCantFocusGained
        // TODO add your handling code here:
        try{
            int stock= Integer.parseInt(fieldStock.getText());
            String cod = fieldCod.getText();
            int id = Integer.parseInt(fieldId.getText());
            String desc = fieldDesc.getText();
            fieldCant.setText("1");
            int cantidad = Integer.parseInt(fieldCant.getText());
            int precio = Integer.parseInt(fieldPrecUnit.getText());
            int total = (precio * cantidad);
            if(stock>0){
                item ++;
                ArrayList lista = new ArrayList();
                modelo = (DefaultTableModel) jTableVentaItems.getModel();
                lista.add(item);
                lista.add(id);
                lista.add(cod);
                lista.add(desc);
                lista.add(cantidad);
                lista.add(precio);
                lista.add(total);
                Object [] obj = new Object[7];
                for (int i=0; i<obj.length;i++){
                    obj[i] = lista.get(i);
                }
                modelo.addRow(obj);
                jTableVentaItems.setModel(modelo);
                fieldPrecTotal.setText(total+"");
                limpiarVenta();
                totalPagar();
            }else{
                JOptionPane.showMessageDialog(null, "El Stock es insuficiente");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Eventfocus cant: "+e.getMessage());
        }
    }//GEN-LAST:event_fieldCantFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            modelo = (DefaultTableModel) jTableVentaItems.getModel();
            modelo.removeRow(jTableVentaItems.getSelectedRow());
            totalPagar();
            fieldCod.requestFocus();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ningun elemento seleccionado para remover\n"+e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLimpiarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarProdActionPerformed
        // TODO add your handling code here:
        LimpiarProd();
    }//GEN-LAST:event_btnLimpiarProdActionPerformed

    private void fieldT2IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldT2IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldT2IdActionPerformed

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
        // TODO add your handling code here:
        boolean flag = false;
        try{
            String cat = JOptionPane.showInputDialog("Ingrese el nombre de la nueva Categoria");
            Integer id =null;
            Boolean estado = true;
            if(!"".equals(cat) && null != cat){
                Categorias c = new Categorias(id, cat, estado);
                cc.insertar(c);
                flag= true;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Error en la carga de la nueva Categoria", 1);
        }
        if (flag){
            JOptionPane.showMessageDialog(null, "Categoria agregada");
            MostrarComboCat();
        }
        
    }//GEN-LAST:event_jLabel8MouseReleased

    private void LimpiarProd(){
        fieldT2Id.setText("");
        fieldT2Cod.setText("");
        fieldT2Desc.setText("");
        fieldT2Cant.setText("");
        fieldT2PrecioCosto.setText("");
        fieldT2PrecioVenta.setText("");
        jComboBox2Categorias.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainPage(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarProductos;
    private javax.swing.JButton btnBorrarProducto;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnExportProduc;
    private javax.swing.JButton btnGuardarProducto;
    private javax.swing.JButton btnInformes;
    private javax.swing.JButton btnLimpiarProd;
    private javax.swing.JButton btnNewVenta;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnResumenVentasDiario;
    private javax.swing.JButton btnVentas;
    private javax.swing.JPanel contBotonesVentas;
    private javax.swing.JPanel contBtnProductos;
    private javax.swing.JPanel contCierreVenta;
    private javax.swing.JPanel contInsertProd;
    private javax.swing.JPanel contMainVenta;
    private javax.swing.JPanel contPanelEntrada;
    private javax.swing.JPanel contSidebarButtons;
    private javax.swing.JPanel contSidebarT2;
    private javax.swing.JPanel contenedorTablat2;
    private javax.swing.JTextField fieldCant;
    private javax.swing.JTextField fieldCod;
    private javax.swing.JTextField fieldDesc;
    private javax.swing.JTextField fieldId;
    private javax.swing.JTextField fieldPrecTotal;
    private javax.swing.JTextField fieldPrecUnit;
    private javax.swing.JTextField fieldStock;
    private javax.swing.JTextField fieldT2Cant;
    private javax.swing.JTextField fieldT2Cod;
    private javax.swing.JTextField fieldT2Desc;
    private javax.swing.JTextField fieldT2Id;
    private javax.swing.JTextField fieldT2PrecioCosto;
    private javax.swing.JTextField fieldT2PrecioVenta;
    private javax.swing.JTextField fieldTotalPagar;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox2Categorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTableArticulos;
    private javax.swing.JTable jTableVentaItems;
    private javax.swing.JTable jTableVentas;
    private javax.swing.JLabel labCod;
    private javax.swing.JLabel labT2Categorias;
    private javax.swing.JLabel labT2Cod;
    private javax.swing.JLabel labT2Cod1;
    private javax.swing.JLabel labT2Desc;
    private javax.swing.JLabel labT2PrecioCosto;
    private javax.swing.JLabel labT2PrecioVenta;
    private javax.swing.JLabel labT2StockDisp;
    private javax.swing.JPanel logoCont;
    private javax.swing.JLabel mainLogo;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JPanel panelCajero;
    private javax.swing.JPanel panelConfig;
    private javax.swing.JPanel panelContEntradaProductos;
    private javax.swing.JPanel panelInformes;
    private javax.swing.JPanel panelNuevaVenta;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel panelVentas;
    private javax.swing.JPanel sidebarMain;
    private javax.swing.JTabbedPane tabsPanel;
    // End of variables declaration//GEN-END:variables

    private void totalPagar(){
        totalPagar =0;
        int numFila = jTableVentaItems.getRowCount();
        for (int i = 0; i < numFila; i++) {
            int cal = Integer.parseInt(String.valueOf(jTableVentaItems.getModel().getValueAt(i, 6)));
            totalPagar += cal;
        }
        fieldTotalPagar.setText(String.valueOf(totalPagar));
    }
}
