/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cantina.vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class SuperSu extends javax.swing.JFrame {

    /**
     * Creates new form SuperSu
     */
    public SuperSu() {
        initComponents();
          try {
           Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/iconos/shopping.png"));
            setIconImage(image);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en icono "+e.toString());
        }
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContAcercaDe = new javax.swing.JPanel();
        labelAcercaDE = new javax.swing.JLabel();
        labelAD1 = new javax.swing.JLabel();
        labelAD2 = new javax.swing.JLabel();
        labelAD3 = new javax.swing.JLabel();
        labelAD4 = new javax.swing.JLabel();
        labelAD5 = new javax.swing.JLabel();
        labelAD6 = new javax.swing.JLabel();
        separatorAD = new javax.swing.JSeparator();
        separatorAD1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(568, 312));
        setMinimumSize(new java.awt.Dimension(568, 312));
        setName("Acerca de"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelContAcercaDe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        panelContAcercaDe.setForeground(new java.awt.Color(102, 102, 102));

        labelAcercaDE.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        labelAcercaDE.setForeground(new java.awt.Color(102, 102, 102));
        labelAcercaDE.setText("Acerca de este Sistema");

        labelAD1.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        labelAD1.setForeground(new java.awt.Color(102, 102, 102));
        labelAD1.setText("Desarrollado por: ");

        labelAD2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelAD2.setForeground(new java.awt.Color(102, 102, 102));
        labelAD2.setText("Lucas Frutos");

        labelAD3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelAD3.setForeground(new java.awt.Color(102, 102, 102));
        labelAD3.setText("Daniel Maldonado");

        labelAD4.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        labelAD4.setForeground(new java.awt.Color(102, 102, 102));
        labelAD4.setText("Contactos:");

        labelAD5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        labelAD5.setForeground(new java.awt.Color(102, 102, 102));
        labelAD5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_whatsapp_25px_1.png"))); // NOI18N
        labelAD5.setText("+595 992 205 206");

        labelAD6.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        labelAD6.setForeground(new java.awt.Color(102, 102, 102));
        labelAD6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cantina/vista/imgs/icons8_whatsapp_25px_1.png"))); // NOI18N
        labelAD6.setText("+595 975 333 205");

        javax.swing.GroupLayout panelContAcercaDeLayout = new javax.swing.GroupLayout(panelContAcercaDe);
        panelContAcercaDe.setLayout(panelContAcercaDeLayout);
        panelContAcercaDeLayout.setHorizontalGroup(
            panelContAcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContAcercaDeLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(labelAcercaDE))
            .addComponent(separatorAD, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(separatorAD1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelContAcercaDeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelAD5))
            .addGroup(panelContAcercaDeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelAD6))
            .addGroup(panelContAcercaDeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelContAcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAD2)
                    .addComponent(labelAD3)))
            .addGroup(panelContAcercaDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAD1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelContAcercaDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAD4))
        );
        panelContAcercaDeLayout.setVerticalGroup(
            panelContAcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContAcercaDeLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(labelAcercaDE)
                .addGap(27, 27, 27)
                .addComponent(labelAD1)
                .addGap(6, 6, 6)
                .addComponent(separatorAD, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAD2)
                .addGap(11, 11, 11)
                .addComponent(labelAD3)
                .addGap(27, 27, 27)
                .addComponent(labelAD4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorAD1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelAD5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelAD6)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContAcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContAcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperSu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAD1;
    private javax.swing.JLabel labelAD2;
    private javax.swing.JLabel labelAD3;
    private javax.swing.JLabel labelAD4;
    private javax.swing.JLabel labelAD5;
    private javax.swing.JLabel labelAD6;
    private javax.swing.JLabel labelAcercaDE;
    private javax.swing.JPanel panelContAcercaDe;
    private javax.swing.JSeparator separatorAD;
    private javax.swing.JSeparator separatorAD1;
    // End of variables declaration//GEN-END:variables
}
